### ISSUE TITLE
开发环境去掉ssl验证不管用

### ISSUE THREAD

**Issue by LiXunGuan** [overtrue/laravel-filesystem-cos#11]
版本信息：laravel8版本+overtrue/laravel-filesystem-cos:2.0

我在`config/filesystem.php`中配置guzzle的参数verify去掉ssl验证，不过貌似不管用

```php
            'guzzle'     => [
                'verify' => false, // 可选，是否关闭 SSL 认证
                'timeout'         => env('COS_TIMEOUT', 60),
                'connect_timeout' => env('COS_CONNECT_TIMEOUT', 60),
            ],
```
运行代码之后还是报错
```
[2022-11-03 00:58:16] production.ERROR: cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://his-filesys-13232212312.cos.ap-shanghai.myqcloud.com/customer_photo%2F20221103%2FJCbybjmGgo0HNwC8iczOtofv6w7IgpaBxIc7ioyj.png {"userId":1,"exception":"[object] (Overtrue\\CosClient\\Exceptions\\Exception(code: 0): cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://his-filesys-13232212312.cos.ap-shanghai.myqcloud.com/customer_photo%2F20221103%2FJCbybjmGgo0HNwC8iczOtofv6w7IgpaBxIc7ioyj.png at D:\\wwwroot\\his\\vendor\\overtrue\\qcloud-cos-client\\src\\Client.php:105)
[stacktrace]
#0 D:\\wwwroot\\his\\vendor\\overtrue\\qcloud-cos-client\\src\\ObjectClient.php(53): Overtrue\\CosClient\\Client->__call()
#1 D:\\wwwroot\\his\\vendor\\overtrue\\flysystem-cos\\src\\CosAdapter.php(67): Overtrue\\CosClient\\ObjectClient->putObject()
#2 D:\\wwwroot\\his\\vendor\\overtrue\\flysystem-cos\\src\\CosAdapter.php(93): Overtrue\\Flysystem\\Cos\\CosAdapter->write()
#3 D:\\wwwroot\\his\\vendor\\league\\flysystem\\src\\Filesystem.php(123): Overtrue\\Flysystem\\Cos\\CosAdapter->writeStream()
#4 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\FilesystemAdapter.php(260): League\\Flysystem\\Filesystem->putStream()
#5 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\FilesystemAdapter.php(296): Illuminate\\Filesystem\\FilesystemAdapter->put()
#6 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\FilesystemAdapter.php(276): Illuminate\\Filesystem\\FilesystemAdapter->putFileAs()
#7 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\FilesystemAdapter.php(252): Illuminate\\Filesystem\\FilesystemAdapter->putFile()
#8 D:\\wwwroot\\his\\app\\Helpers\\Attachment.php(26): Illuminate\\Filesystem\\FilesystemAdapter->put()
#9 D:\\wwwroot\\his\\app\\Http\\Controllers\\CustomerPhotoController.php(71): App\\Helpers\\Attachment->upload()
#10 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): App\\Http\\Controllers\\CustomerPhotoController->upload()
#11 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#12 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#13 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(205): Illuminate\\Routing\\Route->runController()
#14 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(721): Illuminate\\Routing\\Route->run()
#15 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#16 D:\\wwwroot\\his\\app\\Http\\Middleware\\Login.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\Login->handle()
#18 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#20 D:\\wwwroot\\his\\vendor\\stancl\\tenancy\\src\\Middleware\\IdentificationMiddleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 D:\\wwwroot\\his\\vendor\\stancl\\tenancy\\src\\Middleware\\InitializeTenancyByDomain.php(38): Stancl\\Tenancy\\Middleware\\IdentificationMiddleware->initializeTenancy()
#22 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Stancl\\Tenancy\\Middleware\\InitializeTenancyByDomain->handle()
#23 D:\\wwwroot\\his\\vendor\\stancl\\tenancy\\src\\Middleware\\PreventAccessFromCentralDomains.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Stancl\\Tenancy\\Middleware\\PreventAccessFromCentralDomains->handle()
#25 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#27 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#28 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(662): Illuminate\\Routing\\Router->runRoute()
#29 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#30 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#31 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#32 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#34 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#35 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#37 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#38 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#40 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#42 D:\\wwwroot\\his\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#44 D:\\wwwroot\\his\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#46 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#48 D:\\wwwroot\\his\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#49 D:\\wwwroot\\his\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#50 D:\\wwwroot\\his\\server.php(21): require_once('...')
#51 {main}
"} 

```

**Comment by LiXunGuan** [comment]
感谢超哥，问题已解决。
